### ISSUE TITLE
Exhaustive search never finishes running.

### ISSUE THREAD

**Issue by NatPRoach** [nathanweeks/exonerate#16] opened 2019-01-23 03:47 UTC
Hello,
I've been trying to do affine:global alignment using exonerate v2.4.0 . I've tried this using both the conda package, and installing from source as described in the README. Both installation methods result in the same problem: when using the exhaustive search it never seems to end, even when fed extremely short sequences. The command I've been using is as follows:
`/usr/local/bin/./exonerate -S FALSE -E TRUE --showalignment TRUE --showvulgar TRUE -V 9 --model affine:global -Q dna -T dna -q test3.fa -t test4.fa`
As a test I tried aligning 5 bases to one another using this set of inputs, and it still had not finished running after two hours. The same problem for longer sequences. 
The output from this set of inputs is the following: 
```
Command line: [/usr/local/bin/./exonerate -S FALSE -E TRUE --showalignment TRUE --showvulgar TRUE -V 9 --model affine:global -Q dna -T dna -q test3.fa -t test4.fa]
Hostname: [Nathans-MacBook-Pro.local]
** Message: Creating analysis with query[DNA] target[DNA]
** Message: Load query for pairwise comparision [test3] (5)
** Message: Load target for pairwise comparison [test4] (5)
** Message: Load query for pairwise comparision [test3] (5)
** Message: Load target for pairwise comparison [test4] (5)
```
It never seems to get past the loading step. If I run --model affine:local without the -E flag it runs without a problem, but if I include the E flag it fails to finish running as well. It seems like the exhaustive search is never finishing for some reason, even when fed very short sequences.

**Comment by vanbeveren** [comment] 2019-06-03 13:21
Hello,

I'm having a similar issue, although I was using a different model:
`exonerate -q query_proteins.fa -t genome.fa --geneticcode 11 --model protein2genome -E --percent 40 -S no -V 9`

Similarly, in my case I also get stuck while loading the sequences for pairwise comparison. I tested the same command with older version of exonerate (2.2 and 2.3), and it works on both.

Is this issue being worked on? At least for now, as a work around you can probably use version 2.3 (which also supports multithreading, unlike 2.2). It has been a while since this issue was posted, but I hope this will help.

**Comment by ryandward** [comment] 2020-09-20 23:21
Just thought I'd drop by and say I am having the same issue.

**Comment by nathanweeks** [comment] 2020-09-21 16:48
Sorry for the late reply regarding this issue. Could someone provide query & target sequences to help reproduce?

**Comment by MaximePolicarpo** [comment] 2022-05-02 13:43
Hi ! 
This still seems to be an issue. Exonerate with -E True never finishes running with any query/target sequences. 
Maxime

**Comment by nathanweeks** [comment] 2022-05-21 13:11
I've verified that exonerate 2.4.0 (at least the bioconda package) hangs on the following exhaustive search: 
```
$ conda create -c conda-forge -c bioconda -n exonerate exonerate
...
$ conda run -n exonerate exonerate --version
ERROR conda.cli.main_run:execute(41): `conda run exonerate --version` failed. (See above for error)
exonerate from exonerate version 2.4.0
Using glib version 2.70.2
Built on Feb 23 2022

$ conda run -n exonerate exonerate -E --model affine:global -Q dna -T dna -q  test/data/cdna/calm.human.dna.fasta -t test/data/cdna/htrt.human.dna.fasta 
... hangs ...
```
However, exonerate compiled from the master branch of this repo completes:
```
$ docker build -t exonerate https://github.com/nathanweeks/exonerate.git
...
$ alias exonerate='docker run -it --rm -v $PWD:/mnt -w /mnt exonerate'
$ exonerate --version
exonerate from exonerate version 2.4.0
Using glib version 2.64.6
Built on May 21 2022
$ exonerate -E --model affine:global -Q dna -T dna -q  test/data/cdna/calm.human.dna.fasta -t test/data/cdna/htrt.human.dna.fasta
Command line: [/usr/local/bin/exonerate -E --model affine:global -Q dna -T dna -q test/data/cdna/calm.human.dna.fasta -t test/data/cdna/htrt.human.dna.fasta]
Hostname: [da1f1d35e992]

** (process:1): WARNING **: 13:00:47.891: Exhaustively generating suboptimal alignments will be VERY SLOW: use -S no
-- completed exonerate analysis
```
The root cause may have been fixed in this fork subsequent to the original/upstream v2.4.0 release. If someone could test with their data (and verify the results look plausible), that would be helpful.

**Comment by nathanweeks** [comment] 2023-06-10 13:24
I'll consider this issue resolved in the master branch, but if someone is able to provide a query/target that reproduces the issue in exonerate compiled from the master branch, please feel free to reopen.

**Closed by nathanweeks** 2023-06-10 13:24 UTC
